videos:
  - "ChA_zph7aao" # Getting started                      (https://www.youtube.com/watch?v=ChA_zph7aao)
  - "rTsfBAV7sOo" # How to set up individual assignments (https://www.youtube.com/watch?v=rTsfBAV7sOo)
  - "-52quDR2QSc" # How to set up group assignments      (https://www.youtube.com/watch?v=-52quDR2QSc)
